### ISSUE TITLE
Only 1/4 screen is captured when display has a 200% scale setting.

### ISSUE THREAD

**Issue by xiechunhong** [FlaUI/FlaUI#359] opened 2020-06-24 09:28 UTC
![scale_setting](https://user-images.githubusercontent.com/15811194/85528995-306f0b00-b63f-11ea-8cf0-572dc6fb416b.png)
My monitor has the above setting, when running the following code to capture screenshot, only 1/4 is captured. I guess internally, FlaUI doesn't consider the scale setting, so it uses a smaller ScreenWidth and ScreenHeight (1/2 to the actual ScreenWidth and ScreenHeight) to get screenshot.

```
var image = Capture.Screen();
image.ToFile(@"screen.png");
```

**Comment by xiechunhong** [comment] 2020-06-24 09:40
When the scale setting set to 100%, the screen capture is normal (image for whole screen is captured).

**Comment by JonnySunNZ** [comment] 2020-07-15 21:14
@xiechunhong Hi, do you mind posting a snippet of how to get it solved?

**Comment by Roemer** [comment] 2020-07-22 19:52
I am currently investigating here. But it seems not extremely easy, especially for backwards compatibility. I would need to be able to get the DPI setting for each monitor and calculate the effective pixels or make the process DPI per Monitor Aware (which seems to only work from .NET 4.6.1 or higher and on Windows 8.1). Also it is unclear from when on a DPI per Monitor could be set? Maybe also starting from Windows 8.1. I will need to investigate further for this issue. If someone has some information, feel free to help out.

**Comment by Roemer** [comment] 2020-07-22 21:20
I will close this as the issue is tracked in #306.

**Closed by Roemer** 2020-07-22 21:20 UTC
