### ISSUE TITLE
support for parallel testing

### ISSUE THREAD

**Issue by adrian-herscu** [FlaUI/FlaUI#487] opened 2022-04-18 12:03 UTC
**Describe the bug**
Tried to run several UI tests in parallel. Each test holds its own Application and AutomationBase objects in ThreadLocals.

Getting:

```
System.Runtime.InteropServices.COMException : An event was unable to invoke any of the subscribers (0x80040201)

System.Runtime.InteropServices.COMException : An event was unable to invoke any of the subscribers (0x80040201   at Interop.UIAutomationClient.IUIAutomationTreeWalker.GetFirstChildElement(IUIAutomationElement element)
```

If running sequentially it works.

Any undocumented limitation in FlaUI?

**Comment by Roemer** [comment] 2022-06-22 13:41
Duplicate of #492

**Closed by Roemer** 2022-06-22 13:41 UTC
