### ISSUE TITLE
Attach to process on remote computer?

### ISSUE THREAD

**Issue by arpsyapathy** [FlaUI/FlaUI#324] opened 2020-03-26 16:35 UTC
Hi all!
Can i attach to process on remote computer with FlaUI?

**Comment by Roemer** [comment] 2020-05-19 21:36
No this is currently not possible as this would need a complete API/Wrapper. Just copy your automation code to the remote and run it there. It's kind of a duplicate of https://github.com/FlaUI/FlaUI/issues/50

**Closed by Roemer** 2020-05-19 21:36 UTC
